USE ecommerce_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS ORDER_DETAILS;
DROP TABLE IF EXISTS PRODUCT_CATEGORY;
DROP TABLE IF EXISTS `ORDER`;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS VENDOR;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS SYSTEM_MANAGER;

SET FOREIGN_KEY_CHECKS = 1;