USE ecommerce_db;

DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS ORDER_DETAILS;
DROP TABLE IF EXISTS `ORDER`;
DROP TABLE IF EXISTS PRODUCT_CATEGORY;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS VENDOR;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS SYSTEM_MANAGER;

-- SYSTEM_MANAGER
CREATE TABLE SYSTEM_MANAGER (
    ManagerID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

-- CUSTOMER
CREATE TABLE CUSTOMER (
    CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(20),
    CustomerStatus VARCHAR(20) DEFAULT 'Active',
    ShippingAddress VARCHAR(255),
    ManagerID INT,
    FOREIGN KEY (ManagerID) REFERENCES SYSTEM_MANAGER(ManagerID) ON DELETE SET NULL
);

-- VENDOR
CREATE TABLE VENDOR (
    VendorID INT PRIMARY KEY AUTO_INCREMENT,
    VendorName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(20),
    VendorStatus VARCHAR(20) DEFAULT 'Active',
    ManagerID INT,
    FOREIGN KEY (ManagerID) REFERENCES SYSTEM_MANAGER(ManagerID) ON DELETE SET NULL
);

-- PRODUCT
CREATE TABLE PRODUCT (
    ProductID INT PRIMARY KEY AUTO_INCREMENT,
    ProductName VARCHAR(255) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    StockQuantity INT NOT NULL DEFAULT 0,
    Description TEXT,
    CountryOfOrigin VARCHAR(100),
    VendorID INT,
    FOREIGN KEY (VendorID) REFERENCES VENDOR(VendorID) ON DELETE CASCADE
);

-- CATEGORY
CREATE TABLE CATEGORY (
    CategoryID INT PRIMARY KEY AUTO_INCREMENT,
    CategoryName VARCHAR(100) NOT NULL
);

-- PRODUCT_CATEGORY
CREATE TABLE PRODUCT_CATEGORY (
    ProductID INT,
    CategoryID INT,
    PRIMARY KEY (ProductID, CategoryID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE,
    FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID) ON DELETE CASCADE
);

-- ORDER
CREATE TABLE `ORDER` (
    OrderID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT NOT NULL,
    OrderDate DATETIME NOT NULL,
    TotalOrderPrice DECIMAL(10, 2) NOT NULL,
    OrderStatus VARCHAR(50) DEFAULT 'Processing',
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE
);

-- ORDER_DETAILS
CREATE TABLE ORDER_DETAILS (
    OrderID INT,
    ProductID INT,
    Quantity INT NOT NULL,
    TotalProductPrice DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (OrderID, ProductID), 
    FOREIGN KEY (OrderID) REFERENCES `ORDER`(OrderID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE
);

-- REVIEW
CREATE TABLE REVIEW (
    ReviewID INT PRIMARY KEY AUTO_INCREMENT,
    RatingStar INT,
    Comment TEXT,
    Date DATETIME,
    CustomerID INT,
    ProductID INT,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE
);